export const METHOD_GET = "GET";
export const METHOD_POST = "POST";
export const METHOD_PUT = "PUT";
export const METHOD_DELETE = "DELETE";

export const API_CALL_TYPE_DETAILS = "API_TYPE_DETAILS";
export const API_CALL_TYPE_LIST = "API_TYPE_LIST";
export const API_CALL_TYPE_REMOVE = "API_CALL_TYPE_REMOVE";
export const API_CALL_TYPE_AUTHORS = "API_CALL_TYPE_AUTHORS";
export const API_CALL_TYPE_SUBMIT_BOOK = "API_CALL_TYPE_SUBMIT_BOOK";
export const API_CALL_TYPE_SUBMIT_EDIT_BOOK = "API_CALL_TYPE_SUBMIT_EDIT_BOOK";

export const UPDATE_QUERY = "App/UPDATE_QUERY";
export const UPDATE_DETAILS_QUERY = "App/UPDATE_DETAILS_QUERY";
export const LOAD_BOOK_LIST = "App/LOAD_BOOK_LIST";
export const LOAD_BOOK_DETAIL = "App/LOAD_BOOK_DETAIL";
export const LOAD_AUTHOR_LIST = "App/LOAD_AUTHOR_LIST";
export const LOAD_CLEAN_FORM = "App/LOAD_CLEAN_FORM";

export const LOAD_BOOK_LIST_PENDING = "App/LOAD_BOOK_LIST_PENDING";
export const LOAD_BOOK_LIST_FINISHED = "App/LOAD_BOOK_LIST_FINISHED";
export const LOAD_BOOK_LIST_ERROR = "App/LOAD_BOOK_LIST_ERROR";

export const LOAD_BOOK_DETAIL_PENDING = "App/LOAD_BOOK_DETAIL_PENDING";
export const LOAD_BOOK_DETAIL_FINISHED = "App/LOAD_BOOK_DETAIL_FINISHED";
export const LOAD_BOOK_DETAIL_ERROR = "App/LOAD_BOOK_DETAIL_ERROR";

export const SUBMIT_BOOK_PENDING = "App/SUBMIT_BOOK_PENDING";
export const SUBMIT_BOOK_FINISHED = "App/SUBMIT_BOOK_FINISHED";
export const SUBMIT_BOOK_ERROR = "App/SUBMIT_BOOK_ERROR";

export const SUBMIT_BOOK_EDIT_PENDING = "App/SUBMIT_BOOK_EDIT_PENDING";
export const SUBMIT_BOOK_EDIT_FINISHED = "App/SUBMIT_BOOK_EDIT_FINISHED";
export const SUBMIT_BOOK_EDIT_ERROR = "App/SUBMIT_BOOK_EDIT_ERROR";

export const LOAD_AUTHOR_LIST_PENDING = "App/LOAD_AUTHOR_LIST_PENDING";
export const LOAD_AUTHOR_LIST_FINISHED = "App/LOAD_AUTHOR_LIST_FINISHED";
export const LOAD_AUTHOR_LIST_ERROR = "App/LOAD_AUTHOR_LIST_ERROR";

export const BOOK_REMOVE_PENDING = "App/BOOK_REMOVE_PENDING";
export const BOOK_REMOVE_FINISHED = "App/BOOK_REMOVE_FINISHED";
export const BOOK_REMOVE_ERROR = "App/BOOK_REMOVE_ERROR";

export const REMOVE_BOOK_DETAIL = "App/REMOVE_BOOK_DETAIL";

export const SUBMIT_POST_BOOK = "App/SUBMIT_POST_BOOK";
export const SUBMIT_PUT_BOOK = "App/SUBMIT_PUT_BOOK";

export const TYPE_MESSAGE_WARNING = "warning";
export const TYPE_MESSAGE_SUCCESS = "success";

export const LOAD_EDIT_FORM = "App/LOAD_EDIT_FORM";
